version: 1.0.{build}
  
branches:
  only:
  - master 
  
skip_commits:
  files:
    - docs/*
    - '**/*.html'  
    
skip_branch_with_pr: true

skip_tags: true

image: Visual Studio 2017

install: 
- ps: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

configuration: Release

shallow_clone: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
environment:
  matrix:
  - TOKEN:
      secure: EFVcZzUo9GxQ+slLBFQc2zhFzlfA9gULAy0cXu5m6mQbyzRYLxnAw3F+Z0Qx0Jef
    SECRET:
      secure: Wz456M9HIV13gTGBd4Eh1F+EsMcmwKgqJhG44BFaXTdC0TyX3k02vAoqOSMo9Xd7
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
before_build:
- ps: .\Build\version_updater.ps1

build:
  publish_nuget: true
  verbosity: minimal
  
artifacts:
- path: '.\DadataApiClient\bin\**\DadataApiClient.dll'
  name: DadataApiClient.dll
- path: /.*\.nupkg/

deploy:
- provider: NuGet
  api_key:
    secure: MgLMMGChxGhyyhSrWuntCcR83vpMU7geCo8YfmNVFbW8FLtf/GZqQLd3ZdNoMMzY
  skip_symbols: true
  artifact: /.*.nupkg/
  
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
  
cache:
  - packages -> **\packages.config   